# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c620dba7cf40005617c8338c61349e387bfa4a74204a1533c47991cce56e1b242088dd966c70a8ed3a54e8e044cba8a9d3b4fc55a96bb14001dd584d11bddba0

test:
  secret_key_base: 34538680e55df9698957c55e8ff501c2974e07671370c9ae6de371ae6843960db7636f430bef7791df230252189add2bfa94bec28447167fccfd0ba507946184

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
